# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/ecom
#     username: postgres
#     password: admin
#     driver-class-name: org.postgresql.Driver

#   jpa:
#     hibernate:
#       ddl-auto: update
#     open-in-view: false
#     properties:
#       hibernate:
#         format_sql: true

#   flyway:
#     enabled: true
#     locations: classpath:db/migration

#   servlet:
#     multipart:
#       max-file-size: 10MB
#       max-request-size: 50MB

# app:
#   jwt:
#     secret: DEV_SECRET_KEY_FOR_LOCAL_TESTING
#     accessTtlMinutes: 60




spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

app:
  jwt:
    secret: DEV_SECRET_KEY_FOR_LOCAL_TESTING
    accessTtlMinutes: 60

razorpay:
  key-id: rzp_test_xxxxxxxxx
  key-secret: xxxxxxxxxxxxx