





spring:
  application:
    name: mydev-ecommerce

  config:
    import: "optional:file:.env[.properties]"

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  jwt:
    secret: ${JWT_SECRET}
    accessTtlMinutes: 60

razorpay:
  key-id: ${RAZORPAY_KEY_ID:dummy}
  key-secret: ${RAZORPAY_KEY_SECRET:dummy}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}