spring.application.name=mydev-ecommerce



# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/ecom
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT CONFIG
# ===============================
app.jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_64_CHARACTERS
app.jwt.accessTtlMinutes=60

# ===============================
# ACTUATOR (for debugging APIs)
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ===============================
# DEBUG LOGGING (Optional but useful)
# ===============================
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG